[general]
    n = 1_000

[gender]
    quota = [["男", ".51"], ["女", ".49"]]
    remap = [["非二元性别", "男"], ["我不愿回答此问题", "男"]]

[age]
    quota = [
        [
            "18-24",
            ".16",
        ],
        [
            "25-39",
            ".32",
        ],
        [
            "40-54",
            ".29",
        ],
        [
            "55+",
            ".23",
        ],
    ]

[demographics]
    quota = [["low", ".05"], ["medium", ".35"], ["high", ".60"]]
